// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: identity/v1/events.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventMetadata is embedded in every domain event this service publishes.
// event_id lets a downstream consumer deduplicate a redelivered message;
// schema_version starts at 1 and is bumped whenever a message's field
// semantics change in a way consumers must account for.
type EventMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMetadata) Reset() {
	*x = EventMetadata{}
	mi := &file_identity_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMetadata) ProtoMessage() {}

func (x *EventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMetadata.ProtoReflect.Descriptor instead.
func (*EventMetadata) Descriptor() ([]byte, []int) {
	return file_identity_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventMetadata) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventMetadata) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventMetadata) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *EventMetadata) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EventMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// UserRegistered is published once, after a new user successfully
// completes registration.
type UserRegistered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *EventMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegistered) Reset() {
	*x = UserRegistered{}
	mi := &file_identity_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegistered) ProtoMessage() {}

func (x *UserRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegistered.ProtoReflect.Descriptor instead.
func (*UserRegistered) Descriptor() ([]byte, []int) {
	return file_identity_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserRegistered) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UserRegistered) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// UserPreferenceUpdated is published after onboarding, a like/unlike, a
// follow/unfollow, or any other preference-affecting mutation. The
// envelope alone identifies which user and when; it carries no per-field
// diff, since no downstream consumer schema for one exists yet.
type UserPreferenceUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *EventMetadata         `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreferenceUpdated) Reset() {
	*x = UserPreferenceUpdated{}
	mi := &file_identity_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferenceUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferenceUpdated) ProtoMessage() {}

func (x *UserPreferenceUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferenceUpdated.ProtoReflect.Descriptor instead.
func (*UserPreferenceUpdated) Descriptor() ([]byte, []int) {
	return file_identity_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *UserPreferenceUpdated) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_identity_v1_events_proto protoreflect.FileDescriptor

const file_identity_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x18identity/v1/events.proto\x12\videntity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n" +
	"\rEventMetadata\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\x05R\rschemaVersion\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\"^\n" +
	"\x0eUserRegistered\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1a.identity.v1.EventMetadataR\bmetadata\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"O\n" +
	"\x15UserPreferenceUpdated\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1a.identity.v1.EventMetadataR\bmetadataBkZigithub.com/jeelan-ds786/music-recommender-system/music-identity-gatekeeper/internal/event/eventpb;eventpbb\x06proto3"

var (
	file_identity_v1_events_proto_rawDescOnce sync.Once
	file_identity_v1_events_proto_rawDescData []byte
)

func file_identity_v1_events_proto_rawDescGZIP() []byte {
	file_identity_v1_events_proto_rawDescOnce.Do(func() {
		file_identity_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_events_proto_rawDesc), len(file_identity_v1_events_proto_rawDesc)))
	})
	return file_identity_v1_events_proto_rawDescData
}

var file_identity_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_identity_v1_events_proto_goTypes = []any{
	(*EventMetadata)(nil),         // 0: identity.v1.EventMetadata
	(*UserRegistered)(nil),        // 1: identity.v1.UserRegistered
	(*UserPreferenceUpdated)(nil), // 2: identity.v1.UserPreferenceUpdated
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_identity_v1_events_proto_depIdxs = []int32{
	3, // 0: identity.v1.EventMetadata.occurred_at:type_name -> google.protobuf.Timestamp
	0, // 1: identity.v1.UserRegistered.metadata:type_name -> identity.v1.EventMetadata
	0, // 2: identity.v1.UserPreferenceUpdated.metadata:type_name -> identity.v1.EventMetadata
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_identity_v1_events_proto_init() }
func file_identity_v1_events_proto_init() {
	if File_identity_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_events_proto_rawDesc), len(file_identity_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_v1_events_proto_goTypes,
		DependencyIndexes: file_identity_v1_events_proto_depIdxs,
		MessageInfos:      file_identity_v1_events_proto_msgTypes,
	}.Build()
	File_identity_v1_events_proto = out.File
	file_identity_v1_events_proto_goTypes = nil
	file_identity_v1_events_proto_depIdxs = nil
}
