version: 1

updates:
  - package-ecosystem: gomod
    directory: /music-identity-gatekeeper
    schedule:
      interval: weekly
      day: monday
    groups:
      go-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /music-identity-gatekeeper
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
