// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: playback/v1/events.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaybackEventV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SchemaVersion int32                  `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	ProducedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=produced_at,json=producedAt,proto3" json:"produced_at,omitempty"`
	Producer      string                 `protobuf:"bytes,6,opt,name=producer,proto3" json:"producer,omitempty"`
	TraceId       string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	UserId        string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientEventId string                 `protobuf:"bytes,9,opt,name=client_event_id,json=clientEventId,proto3" json:"client_event_id,omitempty"`
	SongId        string                 `protobuf:"bytes,10,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,11,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PositionMs    int64                  `protobuf:"varint,12,opt,name=position_ms,json=positionMs,proto3" json:"position_ms,omitempty"`
	DurationMs    *int64                 `protobuf:"varint,13,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	DeviceType    string                 `protobuf:"bytes,14,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Context       []byte                 `protobuf:"bytes,15,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackEventV1) Reset() {
	*x = PlaybackEventV1{}
	mi := &file_playback_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackEventV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackEventV1) ProtoMessage() {}

func (x *PlaybackEventV1) ProtoReflect() protoreflect.Message {
	mi := &file_playback_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackEventV1.ProtoReflect.Descriptor instead.
func (*PlaybackEventV1) Descriptor() ([]byte, []int) {
	return file_playback_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *PlaybackEventV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PlaybackEventV1) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PlaybackEventV1) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *PlaybackEventV1) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PlaybackEventV1) GetProducedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProducedAt
	}
	return nil
}

func (x *PlaybackEventV1) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *PlaybackEventV1) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *PlaybackEventV1) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaybackEventV1) GetClientEventId() string {
	if x != nil {
		return x.ClientEventId
	}
	return ""
}

func (x *PlaybackEventV1) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *PlaybackEventV1) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlaybackEventV1) GetPositionMs() int64 {
	if x != nil {
		return x.PositionMs
	}
	return 0
}

func (x *PlaybackEventV1) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

func (x *PlaybackEventV1) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *PlaybackEventV1) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_playback_v1_events_proto protoreflect.FileDescriptor

const file_playback_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x18playback/v1/events.proto\x12\vplayback.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xae\x04\n" +
	"\x0fPlaybackEventV1\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\x05R\rschemaVersion\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12;\n" +
	"\vproduced_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"producedAt\x12\x1a\n" +
	"\bproducer\x18\x06 \x01(\tR\bproducer\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x12&\n" +
	"\x0fclient_event_id\x18\t \x01(\tR\rclientEventId\x12\x17\n" +
	"\asong_id\x18\n" +
	" \x01(\tR\x06songId\x12\x1d\n" +
	"\n" +
	"session_id\x18\v \x01(\tR\tsessionId\x12\x1f\n" +
	"\vposition_ms\x18\f \x01(\x03R\n" +
	"positionMs\x12$\n" +
	"\vduration_ms\x18\r \x01(\x03H\x00R\n" +
	"durationMs\x88\x01\x01\x12\x1f\n" +
	"\vdevice_type\x18\x0e \x01(\tR\n" +
	"deviceType\x12\x18\n" +
	"\acontext\x18\x0f \x01(\fR\acontextB\x0e\n" +
	"\f_duration_msBhZfgithub.com/jeelan-ds786/music-recommender-system/music-playback-service/internal/event/eventpb;eventpbb\x06proto3"

var (
	file_playback_v1_events_proto_rawDescOnce sync.Once
	file_playback_v1_events_proto_rawDescData []byte
)

func file_playback_v1_events_proto_rawDescGZIP() []byte {
	file_playback_v1_events_proto_rawDescOnce.Do(func() {
		file_playback_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_playback_v1_events_proto_rawDesc), len(file_playback_v1_events_proto_rawDesc)))
	})
	return file_playback_v1_events_proto_rawDescData
}

var file_playback_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_playback_v1_events_proto_goTypes = []any{
	(*PlaybackEventV1)(nil),       // 0: playback.v1.PlaybackEventV1
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_playback_v1_events_proto_depIdxs = []int32{
	1, // 0: playback.v1.PlaybackEventV1.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 1: playback.v1.PlaybackEventV1.produced_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_playback_v1_events_proto_init() }
func file_playback_v1_events_proto_init() {
	if File_playback_v1_events_proto != nil {
		return
	}
	file_playback_v1_events_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_playback_v1_events_proto_rawDesc), len(file_playback_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_playback_v1_events_proto_goTypes,
		DependencyIndexes: file_playback_v1_events_proto_depIdxs,
		MessageInfos:      file_playback_v1_events_proto_msgTypes,
	}.Build()
	File_playback_v1_events_proto = out.File
	file_playback_v1_events_proto_goTypes = nil
	file_playback_v1_events_proto_depIdxs = nil
}
