// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: streaming/v1/envelopes.proto

package streamingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetryEnvelopeV1 struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OriginalTopic     string                 `protobuf:"bytes,2,opt,name=original_topic,json=originalTopic,proto3" json:"original_topic,omitempty"`
	OriginalPartition int32                  `protobuf:"varint,3,opt,name=original_partition,json=originalPartition,proto3" json:"original_partition,omitempty"`
	OriginalOffset    int64                  `protobuf:"varint,4,opt,name=original_offset,json=originalOffset,proto3" json:"original_offset,omitempty"`
	OriginalKey       []byte                 `protobuf:"bytes,5,opt,name=original_key,json=originalKey,proto3" json:"original_key,omitempty"`
	OriginalPayload   []byte                 `protobuf:"bytes,6,opt,name=original_payload,json=originalPayload,proto3" json:"original_payload,omitempty"`
	SchemaVersion     int32                  `protobuf:"varint,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Attempt           int32                  `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	RetryAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=retry_at,json=retryAt,proto3" json:"retry_at,omitempty"`
	TraceId           string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RetryEnvelopeV1) Reset() {
	*x = RetryEnvelopeV1{}
	mi := &file_streaming_v1_envelopes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryEnvelopeV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryEnvelopeV1) ProtoMessage() {}

func (x *RetryEnvelopeV1) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_envelopes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryEnvelopeV1.ProtoReflect.Descriptor instead.
func (*RetryEnvelopeV1) Descriptor() ([]byte, []int) {
	return file_streaming_v1_envelopes_proto_rawDescGZIP(), []int{0}
}

func (x *RetryEnvelopeV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RetryEnvelopeV1) GetOriginalTopic() string {
	if x != nil {
		return x.OriginalTopic
	}
	return ""
}

func (x *RetryEnvelopeV1) GetOriginalPartition() int32 {
	if x != nil {
		return x.OriginalPartition
	}
	return 0
}

func (x *RetryEnvelopeV1) GetOriginalOffset() int64 {
	if x != nil {
		return x.OriginalOffset
	}
	return 0
}

func (x *RetryEnvelopeV1) GetOriginalKey() []byte {
	if x != nil {
		return x.OriginalKey
	}
	return nil
}

func (x *RetryEnvelopeV1) GetOriginalPayload() []byte {
	if x != nil {
		return x.OriginalPayload
	}
	return nil
}

func (x *RetryEnvelopeV1) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *RetryEnvelopeV1) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *RetryEnvelopeV1) GetRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RetryAt
	}
	return nil
}

func (x *RetryEnvelopeV1) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type DeadLetterEnvelopeV1 struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	OriginalTopic     string                 `protobuf:"bytes,2,opt,name=original_topic,json=originalTopic,proto3" json:"original_topic,omitempty"`
	OriginalPartition int32                  `protobuf:"varint,3,opt,name=original_partition,json=originalPartition,proto3" json:"original_partition,omitempty"`
	OriginalOffset    int64                  `protobuf:"varint,4,opt,name=original_offset,json=originalOffset,proto3" json:"original_offset,omitempty"`
	OriginalKey       []byte                 `protobuf:"bytes,5,opt,name=original_key,json=originalKey,proto3" json:"original_key,omitempty"`
	OriginalPayload   []byte                 `protobuf:"bytes,6,opt,name=original_payload,json=originalPayload,proto3" json:"original_payload,omitempty"`
	SchemaVersion     int32                  `protobuf:"varint,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	FailureClass      string                 `protobuf:"bytes,8,opt,name=failure_class,json=failureClass,proto3" json:"failure_class,omitempty"`
	TraceId           string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	FailedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeadLetterEnvelopeV1) Reset() {
	*x = DeadLetterEnvelopeV1{}
	mi := &file_streaming_v1_envelopes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadLetterEnvelopeV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetterEnvelopeV1) ProtoMessage() {}

func (x *DeadLetterEnvelopeV1) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_v1_envelopes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetterEnvelopeV1.ProtoReflect.Descriptor instead.
func (*DeadLetterEnvelopeV1) Descriptor() ([]byte, []int) {
	return file_streaming_v1_envelopes_proto_rawDescGZIP(), []int{1}
}

func (x *DeadLetterEnvelopeV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeadLetterEnvelopeV1) GetOriginalTopic() string {
	if x != nil {
		return x.OriginalTopic
	}
	return ""
}

func (x *DeadLetterEnvelopeV1) GetOriginalPartition() int32 {
	if x != nil {
		return x.OriginalPartition
	}
	return 0
}

func (x *DeadLetterEnvelopeV1) GetOriginalOffset() int64 {
	if x != nil {
		return x.OriginalOffset
	}
	return 0
}

func (x *DeadLetterEnvelopeV1) GetOriginalKey() []byte {
	if x != nil {
		return x.OriginalKey
	}
	return nil
}

func (x *DeadLetterEnvelopeV1) GetOriginalPayload() []byte {
	if x != nil {
		return x.OriginalPayload
	}
	return nil
}

func (x *DeadLetterEnvelopeV1) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *DeadLetterEnvelopeV1) GetFailureClass() string {
	if x != nil {
		return x.FailureClass
	}
	return ""
}

func (x *DeadLetterEnvelopeV1) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *DeadLetterEnvelopeV1) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

var File_streaming_v1_envelopes_proto protoreflect.FileDescriptor

const file_streaming_v1_envelopes_proto_rawDesc = "" +
	"\n" +
	"\x1cstreaming/v1/envelopes.proto\x12\fstreaming.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x03\n" +
	"\x0fRetryEnvelopeV1\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12%\n" +
	"\x0eoriginal_topic\x18\x02 \x01(\tR\roriginalTopic\x12-\n" +
	"\x12original_partition\x18\x03 \x01(\x05R\x11originalPartition\x12'\n" +
	"\x0foriginal_offset\x18\x04 \x01(\x03R\x0eoriginalOffset\x12!\n" +
	"\foriginal_key\x18\x05 \x01(\fR\voriginalKey\x12)\n" +
	"\x10original_payload\x18\x06 \x01(\fR\x0foriginalPayload\x12%\n" +
	"\x0eschema_version\x18\a \x01(\x05R\rschemaVersion\x12\x18\n" +
	"\aattempt\x18\b \x01(\x05R\aattempt\x125\n" +
	"\bretry_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aretryAt\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\"\x9e\x03\n" +
	"\x14DeadLetterEnvelopeV1\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12%\n" +
	"\x0eoriginal_topic\x18\x02 \x01(\tR\roriginalTopic\x12-\n" +
	"\x12original_partition\x18\x03 \x01(\x05R\x11originalPartition\x12'\n" +
	"\x0foriginal_offset\x18\x04 \x01(\x03R\x0eoriginalOffset\x12!\n" +
	"\foriginal_key\x18\x05 \x01(\fR\voriginalKey\x12)\n" +
	"\x10original_payload\x18\x06 \x01(\fR\x0foriginalPayload\x12%\n" +
	"\x0eschema_version\x18\a \x01(\x05R\rschemaVersion\x12#\n" +
	"\rfailure_class\x18\b \x01(\tR\ffailureClass\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x127\n" +
	"\tfailed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAtB{Zygithub.com/jeelan-ds786/music-recommender-system/music-event-streaming-service/internal/contracts/streamingpb;streamingpbb\x06proto3"

var (
	file_streaming_v1_envelopes_proto_rawDescOnce sync.Once
	file_streaming_v1_envelopes_proto_rawDescData []byte
)

func file_streaming_v1_envelopes_proto_rawDescGZIP() []byte {
	file_streaming_v1_envelopes_proto_rawDescOnce.Do(func() {
		file_streaming_v1_envelopes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_streaming_v1_envelopes_proto_rawDesc), len(file_streaming_v1_envelopes_proto_rawDesc)))
	})
	return file_streaming_v1_envelopes_proto_rawDescData
}

var file_streaming_v1_envelopes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streaming_v1_envelopes_proto_goTypes = []any{
	(*RetryEnvelopeV1)(nil),       // 0: streaming.v1.RetryEnvelopeV1
	(*DeadLetterEnvelopeV1)(nil),  // 1: streaming.v1.DeadLetterEnvelopeV1
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_streaming_v1_envelopes_proto_depIdxs = []int32{
	2, // 0: streaming.v1.RetryEnvelopeV1.retry_at:type_name -> google.protobuf.Timestamp
	2, // 1: streaming.v1.DeadLetterEnvelopeV1.failed_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_streaming_v1_envelopes_proto_init() }
func file_streaming_v1_envelopes_proto_init() {
	if File_streaming_v1_envelopes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_streaming_v1_envelopes_proto_rawDesc), len(file_streaming_v1_envelopes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_streaming_v1_envelopes_proto_goTypes,
		DependencyIndexes: file_streaming_v1_envelopes_proto_depIdxs,
		MessageInfos:      file_streaming_v1_envelopes_proto_msgTypes,
	}.Build()
	File_streaming_v1_envelopes_proto = out.File
	file_streaming_v1_envelopes_proto_goTypes = nil
	file_streaming_v1_envelopes_proto_depIdxs = nil
}
