syntax = "proto3";

package recommendation.v1;

option go_package = "github.com/jeelan-ds786/music-recommender-system/music-event-streaming-service/internal/contracts/recommendationpb;recommendationpb";

import "google/protobuf/timestamp.proto";

message RecommendationFeedbackV1 {
  string event_id = 1;
  string event_type = 2;
  int32 schema_version = 3;
  google.protobuf.Timestamp occurred_at = 4;
  google.protobuf.Timestamp produced_at = 5;
  string producer = 6;
  string trace_id = 7;
  string user_id = 8;
  string recommendation_id = 9;
  string song_id = 10;
  string action = 11;
}