// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.0
// source: identity.proto

package profilepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListenerProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListenerProfileRequest) Reset() {
	*x = GetListenerProfileRequest{}
	mi := &file_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenerProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenerProfileRequest) ProtoMessage() {}

func (x *GetListenerProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenerProfileRequest.ProtoReflect.Descriptor instead.
func (*GetListenerProfileRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

func (x *GetListenerProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetListenerProfileResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Tier                string                 `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	GenreSeeds          []string               `protobuf:"bytes,3,rep,name=genre_seeds,json=genreSeeds,proto3" json:"genre_seeds,omitempty"`
	LanguagePreferences []string               `protobuf:"bytes,4,rep,name=language_preferences,json=languagePreferences,proto3" json:"language_preferences,omitempty"`
	FollowedArtistIds   []string               `protobuf:"bytes,5,rep,name=followed_artist_ids,json=followedArtistIds,proto3" json:"followed_artist_ids,omitempty"`
	LikedSongCount      int32                  `protobuf:"varint,6,opt,name=liked_song_count,json=likedSongCount,proto3" json:"liked_song_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetListenerProfileResponse) Reset() {
	*x = GetListenerProfileResponse{}
	mi := &file_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListenerProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListenerProfileResponse) ProtoMessage() {}

func (x *GetListenerProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListenerProfileResponse.ProtoReflect.Descriptor instead.
func (*GetListenerProfileResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

func (x *GetListenerProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetListenerProfileResponse) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *GetListenerProfileResponse) GetGenreSeeds() []string {
	if x != nil {
		return x.GenreSeeds
	}
	return nil
}

func (x *GetListenerProfileResponse) GetLanguagePreferences() []string {
	if x != nil {
		return x.LanguagePreferences
	}
	return nil
}

func (x *GetListenerProfileResponse) GetFollowedArtistIds() []string {
	if x != nil {
		return x.FollowedArtistIds
	}
	return nil
}

func (x *GetListenerProfileResponse) GetLikedSongCount() int32 {
	if x != nil {
		return x.LikedSongCount
	}
	return 0
}

var File_identity_proto protoreflect.FileDescriptor

const file_identity_proto_rawDesc = "" +
	"\n" +
	"\x0eidentity.proto\x12\videntity.v1\"4\n" +
	"\x19GetListenerProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xf7\x01\n" +
	"\x1aGetListenerProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\x1f\n" +
	"\vgenre_seeds\x18\x03 \x03(\tR\n" +
	"genreSeeds\x121\n" +
	"\x14language_preferences\x18\x04 \x03(\tR\x13languagePreferences\x12.\n" +
	"\x13followed_artist_ids\x18\x05 \x03(\tR\x11followedArtistIds\x12(\n" +
	"\x10liked_song_count\x18\x06 \x01(\x05R\x0elikedSongCount2x\n" +
	"\x0fIdentityService\x12e\n" +
	"\x12GetListenerProfile\x12&.identity.v1.GetListenerProfileRequest\x1a'.identity.v1.GetListenerProfileResponseBqZogithub.com/jeelan-ds786/music-recommender-system/music-identity-gatekeeper/internal/profile/profilepb;profilepbb\x06proto3"

var (
	file_identity_proto_rawDescOnce sync.Once
	file_identity_proto_rawDescData []byte
)

func file_identity_proto_rawDescGZIP() []byte {
	file_identity_proto_rawDescOnce.Do(func() {
		file_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)))
	})
	return file_identity_proto_rawDescData
}

var file_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_identity_proto_goTypes = []any{
	(*GetListenerProfileRequest)(nil),  // 0: identity.v1.GetListenerProfileRequest
	(*GetListenerProfileResponse)(nil), // 1: identity.v1.GetListenerProfileResponse
}
var file_identity_proto_depIdxs = []int32{
	0, // 0: identity.v1.IdentityService.GetListenerProfile:input_type -> identity.v1.GetListenerProfileRequest
	1, // 1: identity.v1.IdentityService.GetListenerProfile:output_type -> identity.v1.GetListenerProfileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_identity_proto_init() }
func file_identity_proto_init() {
	if File_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_proto_goTypes,
		DependencyIndexes: file_identity_proto_depIdxs,
		MessageInfos:      file_identity_proto_msgTypes,
	}.Build()
	File_identity_proto = out.File
	file_identity_proto_goTypes = nil
	file_identity_proto_depIdxs = nil
}
