// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: recommendation/v1/feedback.proto

package recommendationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendationFeedbackV1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType        string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SchemaVersion    int32                  `protobuf:"varint,3,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	ProducedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=produced_at,json=producedAt,proto3" json:"produced_at,omitempty"`
	Producer         string                 `protobuf:"bytes,6,opt,name=producer,proto3" json:"producer,omitempty"`
	TraceId          string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	UserId           string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RecommendationId string                 `protobuf:"bytes,9,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	SongId           string                 `protobuf:"bytes,10,opt,name=song_id,json=songId,proto3" json:"song_id,omitempty"`
	Action           string                 `protobuf:"bytes,11,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecommendationFeedbackV1) Reset() {
	*x = RecommendationFeedbackV1{}
	mi := &file_recommendation_v1_feedback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationFeedbackV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationFeedbackV1) ProtoMessage() {}

func (x *RecommendationFeedbackV1) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_v1_feedback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationFeedbackV1.ProtoReflect.Descriptor instead.
func (*RecommendationFeedbackV1) Descriptor() ([]byte, []int) {
	return file_recommendation_v1_feedback_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendationFeedbackV1) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *RecommendationFeedbackV1) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RecommendationFeedbackV1) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *RecommendationFeedbackV1) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *RecommendationFeedbackV1) GetProducedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProducedAt
	}
	return nil
}

func (x *RecommendationFeedbackV1) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *RecommendationFeedbackV1) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RecommendationFeedbackV1) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendationFeedbackV1) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *RecommendationFeedbackV1) GetSongId() string {
	if x != nil {
		return x.SongId
	}
	return ""
}

func (x *RecommendationFeedbackV1) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_recommendation_v1_feedback_proto protoreflect.FileDescriptor

const file_recommendation_v1_feedback_proto_rawDesc = "" +
	"\n" +
	" recommendation/v1/feedback.proto\x12\x11recommendation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x03\n" +
	"\x18RecommendationFeedbackV1\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12%\n" +
	"\x0eschema_version\x18\x03 \x01(\x05R\rschemaVersion\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12;\n" +
	"\vproduced_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"producedAt\x12\x1a\n" +
	"\bproducer\x18\x06 \x01(\tR\bproducer\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x12+\n" +
	"\x11recommendation_id\x18\t \x01(\tR\x10recommendationId\x12\x17\n" +
	"\asong_id\x18\n" +
	" \x01(\tR\x06songId\x12\x16\n" +
	"\x06action\x18\v \x01(\tR\x06actionB\x86\x01Z\x83\x01github.com/jeelan-ds786/music-recommender-system/music-event-streaming-service/internal/contracts/recommendationpb;recommendationpbb\x06proto3"

var (
	file_recommendation_v1_feedback_proto_rawDescOnce sync.Once
	file_recommendation_v1_feedback_proto_rawDescData []byte
)

func file_recommendation_v1_feedback_proto_rawDescGZIP() []byte {
	file_recommendation_v1_feedback_proto_rawDescOnce.Do(func() {
		file_recommendation_v1_feedback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommendation_v1_feedback_proto_rawDesc), len(file_recommendation_v1_feedback_proto_rawDesc)))
	})
	return file_recommendation_v1_feedback_proto_rawDescData
}

var file_recommendation_v1_feedback_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_recommendation_v1_feedback_proto_goTypes = []any{
	(*RecommendationFeedbackV1)(nil), // 0: recommendation.v1.RecommendationFeedbackV1
	(*timestamppb.Timestamp)(nil),    // 1: google.protobuf.Timestamp
}
var file_recommendation_v1_feedback_proto_depIdxs = []int32{
	1, // 0: recommendation.v1.RecommendationFeedbackV1.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 1: recommendation.v1.RecommendationFeedbackV1.produced_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recommendation_v1_feedback_proto_init() }
func file_recommendation_v1_feedback_proto_init() {
	if File_recommendation_v1_feedback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommendation_v1_feedback_proto_rawDesc), len(file_recommendation_v1_feedback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recommendation_v1_feedback_proto_goTypes,
		DependencyIndexes: file_recommendation_v1_feedback_proto_depIdxs,
		MessageInfos:      file_recommendation_v1_feedback_proto_msgTypes,
	}.Build()
	File_recommendation_v1_feedback_proto = out.File
	file_recommendation_v1_feedback_proto_goTypes = nil
	file_recommendation_v1_feedback_proto_depIdxs = nil
}
